--- 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: openebs
  namespace: kube-system
spec: 
  chart: 
    spec: 
      chart: openebs
      sourceRef: 
        kind: HelmRepository
        name: openebs
        namespace: kube-system
      version: ">=3.0.3"
  install: 
    disableWaitForJobs: true
  interval: 1m0s
  rollback: 
    disableWaitForJobs: true
  upgrade: 
    disableWaitForJobs: true
  values: 
    localprovisioner:
        basePath: /var/openebs/local
    snapshotOperator:
        enabled: true
    ndm:
        enabled: true
    ndmOperator:
        enabled: true
    analytics:
        enabled: true
    crd:
        enableInstall: true
