--- 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: openebs
  namespace: kube-system
spec: 
  chart: 
    spec: 
      chart: openebs
      sourceRef: 
        kind: HelmRepository
        name: openebs
        namespace: kube-system
      version: ">=3.0.3"
  install: 
    disableWaitForJobs: true
  interval: 1m0s
  rollback: 
    disableWaitForJobs: true
  upgrade: 
    disableWaitForJobs: true
  values: 
    analytics: 
      enabled: true
      pingInterval: 24h
    apiserver: 
      affinity: {}
      enabled: true
      healthCheck: 
        initialDelaySeconds: 30
        periodSeconds: 60
      image: openebs/m-apiserver
      imageTag: "2.12.2"
      nodeSelector: {}
      ports: 
        externalPort: 5656
        internalPort: 5656
      replicas: 1
      resources: {}
      sparse: 
        enabled: "false"
      tolerations: []
    cleanup: 
      image: 
        imagePullSecrets: []
        registry: ~
        repository: bitnami/kubectl
        tag: ~
    crd: 
      enableInstall: true
    cstor: 
      enabled: false
      openebsNDM: 
        enabled: false
      pool: 
        image: openebs/cstor-pool
        imageTag: "2.12.2"
      poolMgmt: 
        image: openebs/cstor-pool-mgmt
        imageTag: "2.12.2"
      target: 
        image: openebs/cstor-istgt
        imageTag: "2.12.2"
      volumeMgmt: 
        image: openebs/cstor-volume-mgmt
        imageTag: "2.12.2"
    defaultStorageConfig: 
      enabled: "true"
    featureGates: 
      APIService: 
        address: "0.0.0.0:9115"
        enabled: false
        featureGateFlag: APIService
      ChangeDetection: 
        enabled: false
        featureGateFlag: ChangeDetection
      GPTBasedUUID: 
        enabled: true
        featureGateFlag: GPTBasedUUID
      UseOSDisk: 
        enabled: false
        featureGateFlag: UseOSDisk
      enabled: true
    helper: 
      image: openebs/linux-utils
      imageTag: "3.0.3"
    image: 
      pullPolicy: IfNotPresent
      repository: ""
    imagePullSecrets: []
    jiva: 
      defaultStoragePath: /var/openebs
      enabled: false
      image: openebs/jiva
      imageTag: "2.12.2"
      localpv-provisioner: 
        openebsNDM: 
          enabled: false
      openebsLocalpv: 
        enabled: false
      replicas: 3
    legacy: 
      enabled: true
    localprovisioner: 
      affinity: {}
      basePath: /var/openebs/local
      enableDeviceClass: true
      enableHostpathClass: true
      enableLeaderElection: true
      enabled: true
      healthCheck: 
        initialDelaySeconds: 30
        periodSeconds: 60
      image: openebs/provisioner-localpv
      imageTag: "3.0.0"
      nodeSelector: {}
      replicas: 1
      resources: {}
      tolerations: []
      waitForBDBindTimeoutRetryCount: "12"
    localpv-provisioner: 
      enabled: true
      openebsNDM: 
        enabled: false
    lvm-localpv: 
      enabled: false
    ndm: 
      enabled: true
      filters: 
        enableOsDiskExcludeFilter: true
        enablePathFilter: true
        enableVendorFilter: true
        excludePaths: "/dev/loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd"
        excludeVendors: "CLOUDBYT,OpenEBS"
        includePaths: ""
        osDiskExcludePaths: "/,/etc/hosts,/boot"
      healthCheck: 
        initialDelaySeconds: 30
        periodSeconds: 60
      image: openebs/node-disk-manager
      imageTag: "1.7.0"
      nodeSelector: {}
      probes: 
        enableSeachest: false
      resources: {}
      sparse: 
        count: "0"
        path: /var/openebs/sparse
        size: "10737418240"
      tolerations: []
    ndmExporter: 
      clusterExporter: 
        metricsPort: 9100
        name: ndm-cluster-exporter
        podLabels: 
          name: openebs-ndm-cluster-exporter
      enabled: false
      image: 
        pullPolicy: IfNotPresent
        registry: ~
        repository: openebs/node-disk-exporter
        tag: "1.7.0"
      nodeExporter: 
        metricsPort: 9101
        name: ndm-node-exporter
        podLabels: 
          name: openebs-ndm-node-exporter
    ndmOperator: 
      enabled: true
      healthCheck: 
        initialDelaySeconds: 15
        periodSeconds: 20
      image: openebs/node-disk-operator
      imageTag: "1.7.0"
      nodeSelector: {}
      readinessCheck: 
        initialDelaySeconds: 5
        periodSeconds: 10
      replicas: 1
      resources: {}
      tolerations: []
      upgradeStrategy: Recreate
    nfs-provisioner: 
      enabled: false
    openebs-ndm: 
      enabled: false
    policies: 
      monitoring: 
        enabled: true
        image: openebs/m-exporter
        imageTag: "2.12.2"
    provisioner: 
      affinity: {}
      enableLeaderElection: true
      enabled: true
      healthCheck: 
        initialDelaySeconds: 30
        periodSeconds: 60
      image: openebs/openebs-k8s-provisioner
      imageTag: "2.12.2"
      nodeSelector: {}
      patchJivaNodeAffinity: enabled
      replicas: 1
      resources: {}
      tolerations: []
    rbac: 
      create: true
      kyvernoEnabled: false
      pspEnabled: false
    release: 
      version: "3.0.3"
    serviceAccount: 
      create: true
      name: ~
    snapshotOperator: 
      affinity: {}
      controller: 
        image: openebs/snapshot-controller
        imageTag: "2.12.2"
        resources: {}
      enableLeaderElection: true
      enabled: true
      healthCheck: 
        initialDelaySeconds: 30
        periodSeconds: 60
      nodeSelector: {}
      provisioner: 
        image: openebs/snapshot-provisioner
        imageTag: "2.12.2"
        resources: {}
      replicas: 1
      tolerations: []
      upgradeStrategy: Recreate
    varDirectoryPath: 
      baseDir: /var/openebs
    webhook: 
      affinity: {}
      enabled: true
      failurePolicy: Fail
      healthCheck: 
        initialDelaySeconds: 30
        periodSeconds: 60
      hostNetwork: false
      image: openebs/admission-server
      imageTag: "2.12.2"
      nodeSelector: {}
      replicas: 1
      resources: {}
      tolerations: []
    zfs-localpv: 
      enabled: false
