apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
