apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-pvc
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
